### PR TITLE
Test branch with linter issues

### PR DESCRIPTION
**Pull request by grisov**
Hi Noelia,  

I created another PR from the "test" branch.  
Both py-files have linter issues.  

I also checked the output of the command :
```
git diff -U0 -- addon/
```

I received e-mail notifications about linter problems.  
Is this the right test?  
Could you please write what else I can do for testing.  

I also use your workflows for GitHub Actions and interested in their proper operation ;)  

Have a nice day!

### CODE REVIEW

**Comment by nvdaes** [comment]
Hi Oleksandr, I'm very happy knowing that GitHub Actions are useful for you. I think this is the right test. Let me make some edits to this pull request. My intention is that the GitHub bot can comment when linting errors are found. But if you have received notifications about errors, this is good. I have found a blog post explaining how to use pull_request_target to make comments. Seems it's not well documented in the GitHub official documentation.
I'll request your help for more detailed testing if needed.
Have a nice day, you too ☺

**Comment by nvdaes** [comment]
For reference, the mentioned post is at

https://blog.bugout.dev/2020/10/23/commenting-on-prs-from-github-actions/

**Comment by nvdaes** [comment]
Hi again Oleksandr, I don't find a secure way of using the pull_request_target event for commenting to report linter errors. But you received notifications about linter problems, that is the important thing.

We may lint the code of the repository which originates the pull request checking out its code, but this may not be a secure practice:

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

I found a good example of pull_request_target used in a workflow in GitHub Docs:

https://github.blog/2021-04-28-use-github-actions-manage-docs/

So, at least for now, let's close these test pull requests. BTW, testing I've discovered that some imports have to be removed from placeMarkers. This has been reported by flake8.

Thanks for your help and have a nice weekend!

**Comment by grisov** [comment]
Hi Noelia,  

I'm glad I was able to make a tiny contribution to testing workflows.  
This is a relatively new feature of GitHub, and I'm still new to this.  
I did receive a lot of notifications, as it should have been.  

Thank you for the links to the articles, this helps me better understand the features of using GitHub Actions.  
Since the pull_request_target event has only recently appeared in workflows, I hope that more features related to its processing will appear soon.  

Thank you for pushing me to explore this definitely useful feature of GitHub :)

Have a nice weekend!

**Comment by nvdaes** [comment]
Thank you. I may post an article about GitHub Actions on my spanish NVDA website, contributed by other members of the community, and in this case I'll mention your valuable contribution with this PR, and may mention you as an author of some add-ons.
BTW: Quick Dictionary was recently shared on a spanish mailing list for impaired visual people and they mentioned that the add-on interface is not translated into Spanish, explaining how to use a feature for this reason. Hope this and other add-ons can be registered on the translation system.
Have a nice day.

**Comment by grisov** [comment]
Thank you, Noelia.  
I have many plans to further improve my add-ons, but unfortunately I don't always have enough time for everything.  
So far, only the Quick Dictionary add-on has been published on the community site.  
After the next update, I will make a request to add my add-ons to the translation system.  
But, as far as I understand, developers are working on big changes, and soon the procedure for translating add-ons may change.  

Greetings to Spain!  
My mother has been living in the beautiful city of Murcia for five years now ;)  
I wish you all the best!

**Comment by nvdaes** [comment]
I understand you don't have enough time. But I think it's a good idea
that you request to include your add-ons in the translation system
when you want, so you can discuss it in mr config repo or something.
I'll ask how to register pcKbBrl input add-on too.
I'll send your greetings to the spanish mailing list where your add-on
has been posted.
See you soon

2021-05-01 14:42 GMT+02:00, Oleksandr Gryshchenko ***@***.***>:

**Pull request closed without merging**
