### PR TITLE
Added the ability to manage bookmarks in Microsoft Edge with the UIA feature enabled.

### PR DESCRIPTION
**Pull request by abdel792**
## Link to issue number:

None

### Summary of the issue:

- Added ability to manage bookmarks in Microsoft Edge browser with UIA feature enabled.

### Description of how this pull request fixes the issue:

With this Pull Request, you can add bookmarks, move to them, and so on. with UIA functionality enabled in Microsoft Edge.

### Testing performed:

Tested locally

### Known issues with pull request:

None

### Change log entry:

None

### CODE REVIEW

**Comment by nvdaes** [comment]
Thanks @abdel792: I'll edit this PR to fix linter errors so that all checks pass before merging.
Also, I'll add your name in the copyright of the Python file of the add-on and in the readme. In case you want to be added to an author with your email, you can do it when you want.

**Comment by abdel792** [comment]
Thanks dear @nvdaes,

I'll try to push a commit which should correct the syntax required by GitHub Action

**Comment by nvdaes** [comment]
Hi dear @abdel792: I'll try to edit this PR since seems that linter errors aren't fixed, and now I can try it. Let's see if I can fix them or more work needs to bedone.

**Comment by nvdaes** [comment]
Linter errors have been fixed, according to the following configuration, similar to the style guidelines used in NVDA, at least the last time I looked it:

https://github.com/nvdaes/nvdaAddonWorkflows/blob/main/setup.cfg

@abdel792, for your convenience, you may look the configuration of your editor since spaces seems always be placed before parentheses even in functions, and in case you want to make a PR for NVDA or other projects this may not be acepted or will need fixes.

**Comment by abdel792** [comment]
Hi dear @nvdaes,

Precisely, I had read the first report talking about the length of the lines which must not exceed 110 characters, as well as the opening parentheses, which must always be preceded by a space.

I thought I had fixed it in my second commit though.

Anyway, thanks for the 2 commits you made.

Keep me informed on how the extension works with UIA functionality enabled in Microsoft Edge.

Here, after several tests, it works very well.

Thanks again.

See you soon.

**Comment by nvdaes** [comment]
never should be preceded by a space when it contains arguments or
parameters of functions. Also, functions that do not belong to a class
should be separated by two blank lines.
I will add a note about your contribution in the Python file similar
to @Josephsl, who mentioned that he converted the add-on to Python3 in
2017. I'll add:

# UIA support added by Abdel in 2022

rentheses
pa> as well as the opening parentheses, which must always be preceded
by a space.
open
No, in fact the

2022-07-21 7:52 GMT+02:00, abdel792 ***@***.***>:

**Comment by abdel792** [comment]
Ah OK dear @nvdaes, thanks again, it's very clear now.

Good day to you and keep me informed.

**Comment by nvdaes** [comment]
Great. Also, I think it would be better not to specify something about
IAccessible class, just, for simplify the logic of the code and not to
let something without considering, make an if... else. Now we make a
condition asking if the object belongs to IAccessible, and then anothe
if asking if is an UIA object.
Don't you think it's better to ask if the object is UIA and then to
use an else condition?
If so, you may make the commit or I can do it later.

2022-07-21 8:32 GMT+02:00, abdel792 ***@***.***>:

**Comment by abdel792** [comment]
OK, you're right.

If there can't be a third possibility, a simple 'else' should suffice, but hey, I'll leave it up to you to do that later if you want.

**Comment by nvdaes** [comment]
Thanks @abdel792, I'm going to add you ass a collaborator. Now I have to approve GitHub Actions for each commit you make. Let's see if when you accept the invitation it's not needed.

**Comment by abdel792** [comment]
Thanks @nvdaes, I received your invitation and accepted it.

**Comment by nvdaes** [comment]
Thanks dear @abdel792. When I can I"ll make the if... else commit, update the readme to include changes mentioning you and merge this PR unless you make other commits. Tomorrow there"s an alert due to extreme hot weather, so it will deppends on when I start working.

**Comment by abdel792** [comment]
Hi dear @nvdaes,

I think I haven't forgotten anything about the parts to implement for UIA.

If you find there are tweaks to add, like code formatting, you can do that if you want.

Thanks again for all.

**Comment by nvdaes** [comment]
Hi dear @abdel792:

I've simplified code and created two different functions, onf for going to bookmark with UIA, another one for going without UIA, and each of them is used in different situations in the general moveToBookmark function.
This works very well here too.
I see two issues:

1. When bookmarks are saved with UIA and without UIA in Edge, they are saved in different files. This may be mentioned in the readme.
2. The notes dialog (alt+NVDA+k) cannot be used to move to the selected bookmark when UIA is enabled. I've tried to fix it increasing the delay in core.callLater function without success. I'll wait in case you can fix it, or will try it again when I can, or we can disable this feature with UIA enabled.

**Comment by abdel792** [comment]
Hi dear @nvdaes:

Thanks.

You wrote:

> 1. When bookmarks are saved with UIA and without UIA in Edge, they are saved in different files.

Yes, it's voluntary on my part, it must be 2 different files, one is preceded by the UIA prefix and not the other.

This is because the number of offsets is different depending on the choice of UIA or not.

> 2. The notes dialog (alt+NVDA+k) cannot be used to move to the selected bookmark when UIA is enabled. I've tried to fix it increasing the delay in core.callLater function without success. I'll wait in case you can fix it, or will try it again when I can, or we can disable this feature with UIA enabled.

Here it works fine, I just have to select a bookmark in the Notes dialog, then enter on it, or validate on OK.

I tested with portable versions of NVDA 2022.2 and 2022.1.

**Comment by nvdaes** [comment]
Oh, I tested wit Nvda installed, version 2022.-2. Hope we can fix this.

**Comment by abdel792** [comment]
Hi again dear @nvdaes,

I just did several tests.

In my previous answer, I hadn't merged your last commit yet.

After merging your last edit, I also see the issue you reported.

I just went back with the following command:

    git checkout HEAD~1

Then I rebuilt the addon with the "scons" command.

You can [download it here](http://cyber25.free.fr/nvda-addons/placeMarkers-22.0-dev.nvda-addon).

Test it and if it works well, we'll proceed to a reversion of your last commit.

**Comment by nvdaes** [comment]
Hi dear @abdel792, in fact this works well. We have to revert my last commit. Would you like to do it? I'm releasing a new add-on at this moment, and my intention is to have it ready today.
Otherwise I'll revert the commit tomorrow.

**Comment by abdel792** [comment]
Hi dear @nvdaes,

If you want, I can undo your last commit.

To do this, we have the possibility of using `git revert HEAD` command, but also the following solution:

- `git reset --hard HEAD~1`
- `git push -f abdel edgeUIAFeature`

This second solution has the merit of not keeping the commit containing the error in the history.

**Comment by nvdaes** [comment]
I think it's better to use git revert to learn with previous mistakes. It's not recommended to use git reset --hard once commits have been public. I'd like to equest you to revert my commit.
And if you want procedd to merge or I'll try to see again if I can improve the code without missing functionality. But I'll do it the next weekend or during this week.

**Comment by abdel792** [comment]
Hi dear @nvdaes,

Your commit is very helpful.

In the function goToUIABookmark, It was just necessary to remove the "elif" in the conditions, because each of the conditions must be evaluated as if it were the first time.

Can you test this fix and tell me if it works well for you?

Thanks in advance.

**Comment by nvdaes** [comment]
In fact it works well now!
If you want, make changes in readme and merge, or I'll do during this week.

**Comment by nvdaes** [comment]
Hi dear @abdel792: I'm thinking about changes for 22.0, some like:

- Added support for moving and deleting bookmarks with UIA.
I'll merge this PR probably the next Sunday. If you want to do any further changes or comments, there are always welcome.

**Comment by nvdaes** [comment]
OK:

For the style of indentation you may check this:

https://github.com/nvaccess/nvda/tree/master/tests/lint

I'll keep you informed, probably this weekend.

2022-07-21 8:02 GMT+02:00, abdel792 ***@***.***>:

**Pull request merged**
